export const premierLeagueTeams = [
  {
    team: 'Arsenal',
    location: 'Islington, London, ENG',
    stadium: 'Emirates Stadium',
    value: 'ar',
  },
  {
    team: 'Aston Villa',
    location: 'Aston, Birmingham, ENG',
    stadium: 'Villa Park',
    value: 'av',
  },
  {
    team: 'Bournemouth',
    location: 'Bournemouth, ENG',
    stadium: 'Vitality Stadium',
    value: 'bo',
  },
  {
    team: 'Brentford',
    location: 'Brentford, London, ENG',
    stadium: 'Brentford Community Stadium',
    value: 'br',
  },
  {
    team: 'Brighton & Hove Albion',
    location: 'Brighton and Hove, ENG',
    stadium: 'Amex Stadium',
    value: 'bha',
  },
  {
    team: 'Burnley',
    location: 'Burnley, ENG',
    stadium: 'Turf Moor',
    value: 'bu',
  },
  {
    team: 'Chelsea',
    location: 'Fulham, London, ENG',
    stadium: 'Stamford Bridge',
    value: 'ch',
  },
  {
    team: 'Crystal Palace',
    location: 'Selhurst, Longon, ENG',
    stadium: 'Selhurst Park',
    value: 'cp',
  },
  {
    team: 'Everton',
    location: 'Liverpool, ENG',
    stadium: 'Goodison Park',
    value: 'ev',
  },
  {
    team: 'Fulham',
    location: 'Fulham, London, ENG',
    stadium: 'Craven Cottage',
    value: 'fu',
  },
  {
    team: 'Liverpool',
    location: 'Liverpool, ENG',
    stadium: 'Anfield',
    value: 'lv',
  },
  {
    team: 'Luton Town ',
    location: 'Luton, ENG',
    stadium: 'Kenilworth Road',
    value: 'lt',
  },
  {
    team: 'Manchester City',
    location: 'Manchester, ENG',
    stadium: 'Etihad Stadium',
    value: 'mc',
  },
  {
    team: 'Manchester United',
    location: 'Manchester, ENG',
    stadium: 'Old Trafford',
    value: 'mu',
  },
  {
    team: 'Newcastle United',
    location: 'Newcastle upon Tyne, ENG',
    stadium: "St James' Park",
    value: 'nu',
  },
  {
    team: 'Nottingham Forest',
    location: 'West Bridgford, ENG',
    stadium: 'City Ground',
    value: 'nf',
  },
  {
    team: 'Sheffield United',
    location: 'Sheffield, ENG',
    stadium: 'Bramall Lane',
    value: 'su',
  },
  {
    team: 'Tottenham Hotspur',
    location: 'Tottenham, London, ENG',
    stadium: 'Tottenham Hotspur Stadium',
    value: 'th',
  },
  {
    team: 'West Ham United',
    location: 'Stratford, East London, ENG',
    stadium: 'London Stadium',
    value: 'whu',
  },
  {
    team: 'Wolverhampton Wanderers',
    location: 'Wolverhampton, ENG',
    stadium: 'Molineux Stadium',
    value: 'ww',
  },
];

export const mlsTeams = [
  {
    team: 'Atlanta United FC',
    stadium: 'Mercedes-Benz Stadium',
    location: 'Atlanta, Georgia, USA',
    value: 'atl',
  },
  {
    team: 'Austin FC',
    stadium: 'Q2 Stadium',
    location: 'Austin, Texas, USA',
    value: 'atx',
  },
  {
    team: 'Chicago Fire FC',
    stadium: 'Soldier Field',
    location: 'Chicago, Illinois, USA',
    value: 'chi',
  },
  {
    team: 'Colorado Rapids',
    stadium: "Dick's Sporting Goods Park",
    location: 'Commerce City, Colorado, USA',
    value: 'cr',
  },
  {
    team: 'Columbus Crew SC',
    stadium: 'Lower.com Field',
    location: 'Columbus, Ohio, USA',
    value: 'cc',
  },
  {
    team: 'D.C. United',
    stadium: 'Audi Field',
    location: 'Washington, D.C., USA',
    value: 'dcu',
  },
  {
    team: 'FC Cincinnati',
    stadium: 'TQL Stadium',
    location: 'Cincinnati, Ohio, USA',
    value: 'cin',
  },
  {
    team: 'FC Dallas',
    stadium: 'Toyota Stadium',
    location: 'Frisco, Texas, USA',
    value: 'dtx',
  },
  {
    team: 'Houston Dynamo FC',
    stadium: 'PNC Stadium',
    location: 'Houston, Texas, USA',
    value: 'hou',
  },
  {
    team: 'Inter Miami CF',
    stadium: 'DRV PNK Stadium',
    location: 'Fort Lauderdale, Florida, USA',
    value: 'mia',
  },
  {
    team: 'Los Angeles FC',
    stadium: 'Banc of California Stadium',
    location: 'Los Angeles, California, USA',
    value: 'lafc',
  },
  {
    team: 'LA Galaxy',
    stadium: 'Dignity Health Sports Park',
    location: 'Carson, California, USA',
    value: 'lag',
  },
  {
    team: 'Minnesota United FC',
    stadium: 'Allianz Field',
    location: 'St. Paul, Minnesota, USA',
    value: 'min',
  },
  {
    team: 'Nashville SC',
    stadium: 'Nissan Stadium / TBD New Stadium',
    location: 'Nashville, Tennessee, USA',
    value: 'nsc',
  },
  {
    team: 'New England Revolution',
    stadium: 'Gillette Stadium',
    location: 'Foxborough, Massachusetts, USA',
    value: 'ner',
  },
  {
    team: 'New York City FC',
    stadium: 'Yankee Stadium',
    location: 'New York City, New York, USA',
    value: 'nycfc',
  },
  {
    team: 'New York Red Bulls',
    stadium: 'Red Bull Arena',
    location: 'Harrison, New Jersey, USA',
    value: 'nyrb',
  },
  {
    team: 'Orlando City SC',
    stadium: 'Exploria Stadium',
    location: 'Orlando, Florida, USA',
    value: 'orl',
  },
  {
    team: 'Philadelphia Union',
    stadium: 'Subaru Park',
    location: 'Chester, Pennsylvania, USA',
    value: 'phil',
  },
  {
    team: 'Portland Timbers',
    stadium: 'Providence Park',
    location: 'Portland, Oregon, USA',
    value: 'por',
  },
  {
    team: 'Real Salt Lake',
    stadium: 'Rio Tinto Stadium',
    location: 'Sandy, Utah, USA',
    value: 'rsl',
  },
  {
    team: 'San Jose Earthquakes',
    stadium: 'PayPal Park',
    location: 'San Jose, California, USA',
    value: 'sj',
  },
  {
    team: 'Seattle Sounders FC',
    stadium: 'Lumen Field',
    location: 'Seattle, Washington, USA',
    value: 'sea',
  },
  {
    team: 'Sporting Kansas City',
    stadium: "Children's Mercy Park",
    location: 'Kansas City, Kansas, USA',
    value: 'skc',
  },
  {
    team: 'Toronto FC',
    stadium: 'BMO Field',
    location: 'Toronto, Ontario, Canada',
    value: 'tor',
  },
  {
    team: 'Vancouver Whitecaps FC',
    stadium: 'BC Place',
    location: 'Vancouver, British Columbia, Canada',
    value: 'van',
  },
];
